configure*: fix build error
-I without anything following causes:
( -I -I./sys/nix )
fatal error: config.h: No such file or directory
-L without anything following causes:
error adding symbols: DSO missing from command line